# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 16:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('Telephone_number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=250)),
                ('Surname', models.CharField(max_length=250)),
                ('doctor_admin', models.EmailField(max_length=40)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default='Enter first name name here', max_length=250)),
                ('Surname', models.CharField(default='Enter surname name here', max_length=250)),
                ('first_line_of_address', models.CharField(default='Enter 1st line of address here', max_length=250)),
                ('second_line_of_address', models.CharField(default='Enter 2nd line of address here', max_length=250)),
                ('County', models.CharField(default='Enter your county here', max_length=250)),
                ('City', models.CharField(default='Enter your city here', max_length=250)),
                ('Postcode', models.CharField(default='Enter your postcode here', max_length=250)),
                ('Telephone_number', models.CharField(default='Enter telephone number here', max_length=250)),
                ('profile_pic', models.FileField(upload_to='')),
                ('create', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Doctor'),
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together=set([('doctor', 'doctor_admin')]),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set([('doctor', 'date', 'start_time')]),
        ),
    ]
